### ISSUE TITLE
HttpClient is not able to generate response

### ISSUE THREAD

**Issue by maxmishyn** [tommysack/typo3-restclient#1]
typo3-restclient/Classes/Client/HttpClient.php at line 541 tries to create new HttpClientResponse instance by calling GeneralUtility::makeInstance. As a parametes it tries to pass values from $response array.
Unfortunately looks like GeneralUtility::makeInstance do not pass them to the _construct. So as the result exception is being rised every time.

**Comment by tommysack** [comment]
Hi maxmishyn, I would like to replicate your case. Please give me more details, thanks a lot.
